$(document).ready(function(){
			$("#AMETHYST").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("AMETHYST");
			  $(this).addClass("active");
			});
			$("#POMEGRANATE").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("POMEGRANATE");
			  $(this).addClass("active");
			});
			$("#SUNFLOWER").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("SUNFLOWER");
			  $(this).addClass("active");
			});
			$("#LIGHTGREENISHBLUE").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("LIGHTGREENISHBLUE");
			  $(this).addClass("active");
			});
			$("#PRUNUSAVIUM").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("PRUNUSAVIUM");
			  $(this).addClass("active");
			});
			$("#FADEDPOSTER").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("FADEDPOSTER");
			  $(this).addClass("active");
			});
			$("#DOUBLEDRAGONSKIN").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("DOUBLEDRAGONSKIN");
			  $(this).addClass("active");
			});
			$("#MINTGREEN").click(function(){
				$(".active").removeClass("active");
				$("#Neon").removeClass();
			  $("#Neon").addClass("MINTGREEN");
			  $(this).addClass("active");
			});
		});