<?xml version="1.0" encoding="utf-8"?><Database Name="zahirbk" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-SDVG61S\SQLEXPRESS;Initial Catalog=zahirbk;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zahirbkConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ContactList" Member="ContactList">
    <Type Name="ContactList">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserSurname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>